using FluentMigrator.Builders.Create.Table;

namespace Infrastructure.Mapping.Builders.Catalog;

/// <summary>
/// Represents a product entity builder
/// </summary>
public partial class ProductBuilder : NopEntityBuilder<Product>
{
    #region Methods

    /// <summary>
    /// Apply entity configuration
    /// </summary>
    /// <param name="table">Create table expression builder</param>
    public override void MapEntity(CreateTableExpressionBuilder table)
    {
        table
            .WithColumn(nameof(Product.ProductTypeId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.ParentGroupedProductId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.VisibleIndividually)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.Name)).AsString(400).NotNullable()
            .WithColumn(nameof(Product.ShortDescription)).AsString(int.MaxValue).Nullable()
            .WithColumn(nameof(Product.FullDescription)).AsString(int.MaxValue).Nullable()
            .WithColumn(nameof(Product.AdminComment)).AsString(int.MaxValue).Nullable()
            .WithColumn(nameof(Product.ProductTemplateId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.VendorId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.ShowOnHomepage)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.MetaKeywords)).AsString(400).Nullable()
            .WithColumn(nameof(Product.MetaDescription)).AsString(int.MaxValue).Nullable()
            .WithColumn(nameof(Product.MetaTitle)).AsString(400).Nullable()
            .WithColumn(nameof(Product.AllowCustomerReviews)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.ApprovedRatingSum)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.NotApprovedRatingSum)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.ApprovedTotalReviews)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.NotApprovedTotalReviews)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.SubjectToAcl)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.LimitedToStores)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.Sku)).AsString(400).Nullable()
            .WithColumn(nameof(Product.ManufacturerPartNumber)).AsString(400).Nullable()
            .WithColumn(nameof(Product.Gtin)).AsString(400).Nullable()
            .WithColumn(nameof(Product.IsGiftCard)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.GiftCardTypeId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.OverriddenGiftCardAmount)).AsDecimal().Nullable()
            .WithColumn(nameof(Product.RequireOtherProducts)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.RequiredProductIds)).AsString(1000).Nullable()
            .WithColumn(nameof(Product.AutomaticallyAddRequiredProducts)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.IsDownload)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.DownloadId)).AsInt32().Nullable()
            .WithColumn(nameof(Product.UnlimitedDownloads)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.MaxNumberOfDownloads)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.DownloadExpirationDays)).AsInt32().Nullable()
            .WithColumn(nameof(Product.DownloadActivationTypeId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.HasSampleDownload)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.SampleDownloadId)).AsInt32().Nullable()
            .WithColumn(nameof(Product.HasUserAgreement)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.UserAgreementText)).AsString(int.MaxValue).Nullable()
            .WithColumn(nameof(Product.IsRecurring)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.RecurringCycleLength)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.RecurringCyclePeriodId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.RecurringTotalCycles)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.IsRental)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.RentalPriceLength)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.RentalPricePeriodId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.IsShipEnabled)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.IsFreeShipping)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.ShipSeparately)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.AdditionalShippingCharge)).AsDecimal().NotNullable()
            .WithColumn(nameof(Product.DeliveryDateId)).AsInt32().Nullable()
            .WithColumn(nameof(Product.IsTaxExempt)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.TaxCategoryId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.ManageInventoryMethodId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.ProductAvailabilityRangeId)).AsInt32().Nullable()
            .WithColumn(nameof(Product.UseMultipleWarehouses)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.WarehouseId)).AsInt32().Nullable()
            .WithColumn(nameof(Product.StockQuantity)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.DisplayStockAvailability)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.DisplayStockQuantity)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.MinStockQuantity)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.LowStockActivityId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.NotifyAdminForQuantityBelow)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.BackorderModeId)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.AllowBackInStockSubscriptions)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.OrderMinimumQuantity)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.OrderMaximumQuantity)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.AllowedQuantities)).AsString(1000).Nullable()
            .WithColumn(nameof(Product.AllowAddingOnlyExistingAttributeCombinations)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.DisplayAttributeCombinationImagesOnly)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.NotReturnable)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.DisableBuyButton)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.DisableWishlistButton)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.AvailableForPreOrder)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.PreOrderAvailabilityStartDateTimeUtc)).AsDateTime().Nullable()
            .WithColumn(nameof(Product.CallForPrice)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.Price)).AsDecimal().NotNullable()
            .WithColumn(nameof(Product.OldPrice)).AsDecimal().Nullable()
            .WithColumn(nameof(Product.ProductCost)).AsDecimal().NotNullable()
            .WithColumn(nameof(Product.CustomerEntersPrice)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.MinimumCustomerEnteredPrice)).AsDecimal().Nullable()
            .WithColumn(nameof(Product.MaximumCustomerEnteredPrice)).AsDecimal().Nullable()
            .WithColumn(nameof(Product.BasepriceEnabled)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.BasepriceAmount)).AsDecimal().Nullable()
            .WithColumn(nameof(Product.BasepriceUnitId)).AsInt32().Nullable()
            .WithColumn(nameof(Product.BasepriceBaseAmount)).AsDecimal().Nullable()
            .WithColumn(nameof(Product.BasepriceBaseUnitId)).AsInt32().Nullable()
            .WithColumn(nameof(Product.MarkAsNew)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.MarkAsNewStartDateTimeUtc)).AsDateTime().Nullable()
            .WithColumn(nameof(Product.MarkAsNewEndDateTimeUtc)).AsDateTime().Nullable()
            .WithColumn(nameof(Product.Weight)).AsDecimal().NotNullable()
            .WithColumn(nameof(Product.Length)).AsDecimal().NotNullable()
            .WithColumn(nameof(Product.Width)).AsDecimal().NotNullable()
            .WithColumn(nameof(Product.Height)).AsDecimal().NotNullable()
            .WithColumn(nameof(Product.AvailableStartDateTimeUtc)).AsDateTime().Nullable()
            .WithColumn(nameof(Product.AvailableEndDateTimeUtc)).AsDateTime().Nullable()
            .WithColumn(nameof(Product.DisplayOrder)).AsInt32().NotNullable()
            .WithColumn(nameof(Product.Published)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.Deleted)).AsBoolean().NotNullable()
            .WithColumn(nameof(Product.CreatedOnUtc)).AsDateTime().NotNullable()
            .WithColumn(nameof(Product.UpdatedOnUtc)).AsDateTime().NotNullable();
    }

    #endregion
}
